# Testes de Autenticação - Wedding API

### Variáveis
@baseUrl = http://localhost:8080/v1
@email = admin@gmail.com
@password = 123456

###

# Registrar novo usuário
POST {{baseUrl}}/usuarios/registrar
Content-Type: application/json

{
  "nome": "luis",
  "email": "{{email}}",
  "telefone": "(11) 99999-9999",
  "senha": "{{password}}"
}

###

# Login do usuário
POST {{baseUrl}}/usuarios/login
Content-Type: application/json

{
  "email": "{{email}}",
  "senha": "{{password}}"
}

> {%
  client.global.set("authToken", response.body.token);
%}