# Testes de Eventos - Wedding API

### Variáveis
@baseUrl = http://localhost:8080/v1
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjAxOTUyOTUsImlhdCI6MTc1OTU5MDQ5NSwic3ViIjoiOGNiZjRhOWUtYTI0OS00YmRkLWI1NjItOWY3NWFlNzg3ZDIzIn0.vUne8wwaShORuW4cJFPrhmRZYUZCeh69xC562k7eJFA

###

# Criar novo evento
POST {{baseUrl}}/eventos
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "nome": "Casamento João & Maria",
  "data": "2024-06-15T15:00:00Z",
  "tipo": "CASAMENTO",
  "urlSlug": "joao-2025"
}

> {%
  client.global.set("eventoId", response.body.idEvento);
%}

###

# Buscar evento por slug (exemplo)
GET {{baseUrl}}/eventos/luis-vivian

###

GET {{baseUrl}}/eventos/id/0aadab2e-bfc6-4610-9c84-7b2c02343463
Authorization: Bearer {{authToken}}



###

# Listar eventos do usuário (exemplo)
GET {{baseUrl}}/eventos
Authorization: Bearer {{authToken}}