name: Build Image

on:
  pull_request:
    branches: [main, hml]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Define image tags
        id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "hml" ]]; then
            echo "TAGS=neuraptor/adminbackend:hml" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAGS=neuraptor/adminbackend:latest,neuraptor/adminbackend:${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "TAGS=neuraptor/adminbackend:latest" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: neuraptor/adminbackend:latest